### ISSUE TITLE
Warning for highly out-of-range ages

### ISSUE THREAD

**Issue by jlapaijmans** [EvolEcolGroup/tidysdm#16]
Problem: no obvious warning message when sample ages are very much out of range (for example, when forgetting to change carbon dates into negative numbers)

Solution:
1. Create a warning message when sample ages are positive (ie in the future)
2. Create a warning message when sample ages are too far outside the boundaries of the age range of the climate dataset (eg more than half the time step size outside of the min and max boundaries)

`pastclim` could potentially also benefit from implementation of the second warning

**Comment by dramanica** [comment]
This is now implemented in pastclim with 1307a0aacd58faa51620ee2fff6c94b05f1e18c1

**Comment by dramanica** [comment]
fixed in ae4427e
