### ISSUE TITLE
Categorical predictors not supported?

### ISSUE THREAD

**Issue by djensing** [EvolEcolGroup/tidysdm#44]
Hello, 
I've run into an issue with unexpected behaviour when using categorical predictor layers (decimal place values for generating variable response curves, etc.), the levels of which are coded with numbers. Things fail if I coerce the raster to a factor... I'm not surprised necessarily that it treats my categorical input layer as a numeric layer (which generates the weird response curves, of course), but as far as I can tell, categorical predictors (e.g. land cover types) are not mentioned in the tidysdm vignettes (searches for 'factor', 'categor', 'ordinal' returned 0 hits) . tidymodels has some discussion of how categorical predictors are handled in the 'Dummies' vignette, but it's not immediately clear to me how this would translate to tidysdm. Mixed predictor variable types are a feature of random forests, maxent etc. that make them appealing options for niche modeling, so are categorical predictors supported in tidysdm, and if so, how do I ensure they're being treated correctly by the models?
Thanks for the great package and vignettes!

**Comment by dramanica** [comment]
There is now a section on the website illustrating how to use `recipes::step_dummy()` to deal with multi-level (categorical) factors.
