### ISSUE TITLE
predict_raster for more than two classes

### ISSUE THREAD

**Issue by piabenaud** [EvolEcolGroup/tidysdm#45]
I came across your package when trying to find a streamline way to predict rasters with classification data. I love your predict_raster function for this, but it fell over as I had more than two classes (I'm doing multi-species classification rather than presence/absence). Just in case it's useful to others, I changed line 31 as follows:

from: `levels(pred_raster) <- data.frame(id = 1:2, class = levels(pred_df %>% dplyr::pull(1)))`

to: `levels(pred_raster) <- data.frame(id = 1:length(pull(unique(pred_df))), class = levels(pred_df %>% dplyr::pull(1)))`

**Comment by dramanica** [comment]
@piabenaud Thanks for sharing this! I haven't really catered for multilevel models (it is on the "it would be nice some day" list). But your solution elegantly solves the problem for `predict_raster()`, do you want to put through a pull request and we'll integrate your solution into the next version of `tidysdm`?
