### ISSUE TITLE
Can 'const' argument (terra::predict) be made with predict_raster for simple_ensemble obj?

### ISSUE THREAD

**Issue by rylielrobinson** [EvolEcolGroup/tidysdm#58]
Hello - I am interesting in using the tidysdm package as the basis for my ensemble ML modelling for a pres/abs study. I have had success with the pipeline up until predicting my simple_ensemble across a raster stack. 

I consider _seasons_ as a categorical (now dummy) variable in my workflow. All other predictors are numeric, which I have rasters for. 

Before going the ensemble route, I created a ranger (random forest) object and predict it across a raster stack using `terra::predict`. When I wanted to predict my ranger model across the spatial extent I was successful using the following code:

```r
list_rf <- list()
seasons <- unique(pnts_r$seasons)
# loop through each season
for(i in 1:4) {
  list_rf[[i]] <- terra::predict(raster_stack, model, type = "response", const = data.frame(season = season[i]))
}
```
However, the _const_ argument does not seem available for the `tidysdm::predict_raster` function for a simple_ensemble object. I have tried (unsuccessfully) to convert seasons to numeric values in hopes to supplement the season as a empty raster in the stack to no avail. 
```r
Error: [`[<-`(i)] the type of index i is unexpected: NULL
```
Trying to predict the simple_ensemble using `terra::predict` no longer works either
```
Error in v[cells, ] <- predv : incorrect number of subscripts on matrix
In addition: Warning message:
Unknown or uninitialised column: `xlevels`.
```
As a `terra::predict` argument _const_ is a 'data.frame. Can be used to add a constant value as a predictor variable so that you do not need to make a SpatRaster layer for it'.

I am interested to know if something like this can be applied for `tidysdm` simple_ensemble objects for spatial/raster predictions?

**Comment by dramanica** [comment]
Hi @rylielrobinson, could you please provide us with a reprex (minimalistic dataset and code) that shows the issues, and we can then look into it. If you have dummy variables for the categorical variable, I am not clear why `predict_raster()` would not work.

**Comment by dramanica** [comment]
To predict a factor that you transformed into a dummy variable in your recipe, you simply need to have a raster with the same categorical variable. So, if we use the ensemble with a 3 level topography variable as shown in the example at the end of https://evolecolgroup.github.io/tidysdm/articles/a2_tidymodels_additions.html#using-multi-level-factors-as-predictors,
I can simply write:
```
# load the raster
climate_present <- terra::readRDS(system.file("extdata/lacerta_climate_present_10m.rds",
                                              package = "tidysdm"))
# first we add the categorical topography variable to the climate data (using the same rules used in the original data.frame)
# most of the time, you wouldn't need this, as the variable would already be in your input file
climate_present$topography <- climate_present$altitude
climate_present$topography <- classify(climate_present$topography, rcl = c(-Inf, 200, 800, Inf), include.lowest=TRUE, brackets=TRUE)
levels(climate_present$topography)  <- data.frame(ID = c(0,1,2), topography = c("plains", "hills", "mountains"))
# now we can predict
predict_factor <- predict_raster(lacerta_ensemble, climate_present)
plot(predict_factor)
```
You need to make sure that your variable is categorical (a factor) both in the data.frame passed to the recipe with `step_dummy()`, and in the raster, and that the name of the variable (and levels) match. Generally, you would have that categorical variable in a raster and then sample from it, so everything should be in sync.
Let me know if you encounter any further problem.

**Comment by dramanica** [comment]
@rylielrobinson Is this issue resolved? If so, we can close it?

**Comment by rylielrobinson** [comment]
@dramanica this approach has worked for the reprex data - thanks

**Comment by joeflangley** [comment]
Thank you for this explanation @dramanica 

I'm interested in exploring multilevel models using DALEX. I tried creating an explainer object using `explain_tidysdm()` but ended up with warning messages for the predicted values and residuals. Is there a way around this for multilevel models?

```{r}
library(tidysdm)

# Load climate raster and prepared occurrences
climate_present <- terra::rast(system.file("extdata/lacerta_climate_present_10m.nc",
                                              package = "tidysdm"))

lacerta_thin <- terra::readRDS(system.file("extdata/lacerta_climate_sf.RDS",
                                    package = "tidysdm"))

# Add a topography variable with 3 levels
lacerta_thin$topography <- cut(lacerta_thin$altitude,
                               breaks = c(-Inf, 200, 800, Inf),
                               labels = c("plains", "hills", "mountains"))

# Subset variables
lacerta_thin <- lacerta_thin %>% select(class, bio05, bio06, bio12, bio15, topography)

# Create recipe
lacerta_rec <- recipe(lacerta_thin, formula = class ~ .) %>%
  step_dummy(topography)
lacerta_prep <- prep(lacerta_rec)
lacerta_bake <- bake(lacerta_prep, new_data = lacerta_thin)

# Define models
lacerta_models <-
  workflow_set(
    preproc = list(default = lacerta_rec),
    models = list(
      glm = sdm_spec_glm(),
      rf = sdm_spec_rf()
    ),
    cross = TRUE
  ) %>%
  option_add(control = control_ensemble_grid())

lacerta_cv <- spatial_block_cv(lacerta_thin, v = 3)
lacerta_models <-
  lacerta_models %>%
  workflow_map("tune_grid",
               resamples = lacerta_cv, grid = 3,
               metrics = sdm_metric_set(), verbose = TRUE
  )

# Fit ensemble
lacerta_ensemble <- simple_ensemble() %>%
  add_member(lacerta_models, metric = "boyce_cont")

# Apply the code you provided to the raster
climate_present$topography <- climate_present$altitude
climate_present$topography <- classify(climate_present$topography, rcl = c(-Inf, 200, 800, Inf), include.lowest=TRUE, brackets=TRUE)
levels(climate_present$topography)  <- data.frame(ID = c(0,1,2), topography = c("plains", "hills", "mountains"))

# Create explainer object
explainer_dormouse_ens <- explain_tidysdm(lacerta_ensemble)
Preparation of a new explainer is initiated
  -> model label       :  data.frame  (  default  )
  -> data              :  452  rows  6  cols 
  -> data              :  tibble converted into a data.frame 
  -> target variable   :  452  values 
  -> predict function  :  predict_function 
  -> predicted values  :  No value for predict function target column. (  default  )
  -> model_info        :  package tidysdm , ver. 0.9.5 , task classification (  default  ) 
  -> model_info        :  type set to  classification 
  -> predicted values  :  the predict_function returns an error when executed (  WARNING  ) 
  -> residual function :  difference between y and yhat (  default  )
  -> residuals         :  the residual_function returns an error when executed (  WARNING  ) 
  A new explainer has been created!  
```

Thank you in advance!

**Comment by dramanica** [comment]
@joeflangley the problem seems to be that we try to extract the data from the workflow, but by that time `step_dummy()` has already be applied. The solution is to give the data explicitly:
```
explainer_dormouse_ens <- explain_tidysdm(lacerta_ensemble, data=lacerta_thin)
```
works just fine for me. We might have to force explicitly passing the data all the time if the recipe is not the most basic option without additional steps.

**Comment by dramanica** [comment]
With ac92c62d56aa880a1e6d575c074153eea2fc4299, now in `dev`, if the data is not provided and we have steps in the recipe, we get the error:
```
# Error: your recipe contains steps; please provide a copy of the original dataset as 'data' argument
```
which is hopefully informative.

**Comment by dramanica** [comment]
Thanks @rylielrobinson for highlighting this bug in `explain_tidysdm()`.
