### ISSUE TITLE
Anaconda package

### ISSUE THREAD

**Issue by Aguncan** [EvolEcolGroup/tidysdm#61]
I can not find tidysdm and pastclim r packages in Anaconda Environment.
Please check  https://repo.anaconda.com/pkgs/r/

**Comment by dramanica** [comment]
I am afraid we haven't created conda recipes for those packages yet. If anyone wants to help with that, it would be appreciated. The process is described here:
https://conda-forge.org/docs/maintainer/adding_pkgs/

**Comment by dramanica** [comment]
`pastclim` is now making its way into conda-forge: https://github.com/conda-forge/staged-recipes/pull/28076
`tidysdm` will follow once that is accepted. 
No builds for windows, as `r-terra` currently does not build on that platform.

**Comment by dramanica** [comment]
`pastclim` is now on conda-forge: https://anaconda.org/conda-forge/r-pastclim

**Comment by dramanica** [comment]
Unfortunatly `tidysdm` is more problematic, as there are no conda packages for `dalextra` and `spatialsample`:
https://github.com/conda-forge/staged-recipes/pull/28195

**Comment by dramanica** [comment]
We now have `tidysdm` on conda-forge as well:
https://anaconda.org/conda-forge/r-tidysdm
Many thanks to @mfansler for his support on making this happen!
