### ISSUE TITLE
Error with workflow_map when maxent is in the workflow_set

### ISSUE THREAD

**Issue by ManuelSpinola** [EvolEcolGroup/tidysdm#65]
I was running the following script just fine, but for some reason now it only works if I remove maxent from the workflow_set.  Any clue what happened?

```{r}
points_models_8 <-
  # create the workflow_set
  workflow_set(
    preproc = list(default = recipe_8),
    models = list(
      # the standard glm specs
      glm = sdm_spec_glm(),
      # rf specs with tuning
      rf = sdm_spec_rf(),
      # boosted tree model (gbm) specs with tuning
      gbm = sdm_spec_boost_tree(),
      # maxent specs with tuning
      maxent = sdm_spec_maxent()
    ),
    # make all combinations of preproc and models,
    cross = TRUE
  ) %>%
  # tweak controls to store information needed later to create the ensemble
  option_add(control = control_ensemble_grid())
```

```{r}
set.seed(1234567)
points_models_7 <-
  points_models_7 %>%
  workflow_map("tune_grid",
    resamples = points_cv_7, grid = 3,
    metrics = sdm_metric_set(), verbose = TRUE
  )
```

No tuning parameters. `fit_resamples()` will be attempted
i 1 of 4 resampling: default_glm
✔ 1 of 4 resampling: default_glm (117ms)
i 2 of 4 tuning:     default_rf
i Creating pre-processing data to finalize unknown parameter: mtry
✔ 2 of 4 tuning:     default_rf (2.9s)
i 3 of 4 tuning:     default_gbm
i Creating pre-processing data to finalize unknown parameter: mtry
✔ 3 of 4 tuning:     default_gbm (3.5s)
i 4 of 4 tuning:     default_maxent
→ A | error:   the condition has length > 1
There were issues with some computations   …
Warning: All models failed. Run `show_notes(.Last.tune.result)` for more information.Warning: Unknown or uninitialised column: `.notes`.✖ 4 of 4 tuning:     default_maxent failed with

**Comment by dramanica** [comment]
Without a reprex it is really impossible to diagnose why maxent might fail. If you can provide a small reprex, then we can look into it.

**Comment by ManuelSpinola** [comment]
Thank you. I don't know if this make sense but if I change the levels of the class from "pseudoabs" to "background", the maxent option works.

**Comment by dramanica** [comment]
Hi @ManuelSpinola, I am not sure why that would be the case. If you can please create a small reprex of the code, I can then investigate.

**Comment by ManuelSpinola** [comment]
If you want, I can send you the dataset and code.

**Comment by dramanica** [comment]
Yes, please, but can you try to minimise the size of the dataset and reduce the code to the minimum that recreates the error?

**Comment by dramanica** [comment]
@ManuelSpinola any update on this?

**Comment by ManuelSpinola** [comment]
My problem was fixed. I guess was some internal error in my script.

*Manuel Spínola, Ph.D.*
Instituto Internacional en Conservación y Manejo de Vida Silvestre
Universidad Nacional
Apartado 1350-3000
Heredia
COSTA RICA
***@***.*** ***@***.***>
***@***.***
Teléfono: (506) 8706 - 4662
Sitio web institucional: ICOMVIS
<http://www.icomvis.una.ac.cr/index.php/manuel>
Sitio web personal: Sitio personal <https://mspinola-sitioweb.netlify.app>
Blog sobre Ciencia de Datos: Blog de Ciencia de Datos
<https://mspinola-ciencia-de-datos.netlify.app>

**Comment by dramanica** [comment]
Ok, we  can then close this issue.
