### ISSUE TITLE
Feature request: stratification for thinning functions

### ISSUE THREAD

**Issue by japilo** [EvolEcolGroup/tidysdm#9]
First of all, thanks for the great and helpful package! Up until now I've had to code up spatiotemporal thinning methods on my own, and it's so convenient to have a pre-written function for this.

For now, I can write up code to implement this on my own, but I think it would be great if there were a built-in capability for the thinning functions to be stratified by a variable of your choice (the way the `initial_split` function in `rsample` can be stratified.)

**Comment by dramanica** [comment]
Thanks for the suggestion. Can you elaborate a bit more on what scenario are you trying to cater for and exactly how that would work? Would the thinning be equivalent to thinning each level in `group` independently?

**Comment by dramanica** [comment]
I don't quite understand what you are trying to achieve. When we thin by cell, we keep a random record so that that particular cell will be used as a presence later on. So, why would you care whether or not you are balancing the origin of the points? The presence will be assigned the characteristics of the cell, irrespective of its origin.

**Comment by japilo** [comment]
I see your point for thinning by cell, but for thinning by distance, you could end up with a situation where very few presence records remain from one source or another.

**Comment by dramanica** [comment]
Ok, now I get what you are after. But I don't see how it would work with the current version of the algorithm. Right now, at any given step, we choose the location with the most neighbours (line 66 in "thin_by_dist.R"). One would have to change the algorithm (as suggested in the note on line 63) where we sample proportionally based on the number of neighbours, and then adjust those probabilities based on the strata proportions. A bit convoluted, but I suppose it could work that way.

**Comment by dramanica** [comment]
@japilo As this is a bit of a corner case, I doubt I'll get to it any time soon. Unless you want to take on this challenge, I'll close this issue for the moment, but happy to reopen it if you decide to work on it.
